### ISSUE TITLE
classe vente problème

### ISSUE THREAD

**Issue by remikaze** [emeric254/Web-STRI-S2-Encheres#24]
quand 2 utilisaeurs sont à enchérir sur une meme annonce, augmentation du prix uniquement de la valeur du pas. si un autre vient enchérir et que celle saisie par le premier utilisateur est supérieur (ou au dessus de 2 fois le pas) il y a une augmentation jusqu'à ce qu'un des deux ne puisse plus enchérir

**Comment by emeric254** [comment]
cf performance optimisation

**Comment by emeric254** [comment]
comportement valide mais performance mediocre ...
