### ISSUE TITLE
vue/recherche.php

### ISSUE THREAD

**Issue by remikaze** [emeric254/Web-STRI-S2-Encheres#26]
début code ligne 89

foreach ($listCat as $idCat => $nomCat) {
    echo "                                        <option value='null'>Toute les categories</option>\n";
    if(isset($cat) and !empty($cat)){....

Modifier et sortir le "toutes les catégories" de dans la boucle foreach car doit etre affiché qu'une fois

**Comment by emeric254** [comment]
C'est fait dans dev-php

**Comment by emeric254** [comment]
fait
