### ISSUE TITLE
traitementinscription

### ISSUE THREAD

**Issue by remikaze** [emeric254/Web-STRI-S2-Encheres#27]
ligne 162 => $_SESSION['idstatut'] = '2'; 

c'est pas un int ? donc sans le simple quote .. ?

**Comment by Gui-B** [comment]
euuuuuuuuuuuuuuuuuuuuuu
        $_SESSION['idville'] = $donnees['idville'];
        $_SESSION['idstatut'] = $donnees['idville'];
dans traitementInscription.php
ça marche bien xD
