### ISSUE TITLE
Fonction test code postal

### ISSUE THREAD

**Issue by remikaze** [emeric254/Web-STRI-S2-Encheres#28]
elle ne marchait pas, cherchait exactement le code postal mais selon les endroits (style toulouse) il y avait plusieurs code pour un meme endroits, et ils sont séparés par un "-" donc le test (a=?) ne marchait pas. 

Voir si modif ok ou si faire autrement

ligne 257 du model.php

**Comment by Gui-B** [comment]
Je m'en oqp

**Comment by Gui-B** [comment]
#78311c625c08ad683d821b5a8e08e4c2abc19f70

**Comment by Gui-B** [comment]
Fonctionelle et mergé
