### ISSUE TITLE
traitementinscription.php

### ISSUE THREAD

**Issue by remikaze** [emeric254/Web-STRI-S2-Encheres#32]
à partir de la ligne 178 : voir si tout ce qui est en commentaire (/\* .... */) peut etre supprimer et éventuellement réutiliser les messages d'erreur. l'upload d'image marchait pas du tout j'ai du recommencer cette partie de code

**Comment by Gui-B** [comment]
Enorme description de probléme xD

**Comment by Gui-B** [comment]
if ($verif==0)
                    {
                        $errMsg="Erreur pendant l'enregistrement de l'inscription.";
                        include_once("vue/erreur.php");
                        include_once("vue/inscription.php");
                    } LA LIGNE 178 !!!!!!!!!!!!!!!!!!!!
                    else
                    {
                        // on stocke

**Comment by remikaze** [comment]
Regarde le titre, du coup vu que l'inscription on l'a géré dans la branche dev-php-inscription c'est sur cette branche.

Possible qu'on ai modifié le fichier ce soir

**Comment by emeric254** [comment]
du coup c closed donc
